/* eslint-disable */
/* This file is auto-generated by tangrams. Do not edit. */

import { queryOptions } from "@tanstack/react-query"

import { getContribRepos, getOmnidotdevRepos, getOwnedRepos, getRepositoryWithReadme } from "../functions"

import type { GetRepositoryWithReadmeQueryVariables } from "./../schema"

// Query Options
export const getOwnedReposQueryOptions = () =>
  queryOptions({
  queryKey: ["github", "GetOwnedRepos"],
  queryFn: () => getOwnedRepos(),
})

export const getOmnidotdevReposQueryOptions = () =>
  queryOptions({
  queryKey: ["github", "GetOmnidotdevRepos"],
  queryFn: () => getOmnidotdevRepos(),
})

export const getContribReposQueryOptions = () =>
  queryOptions({
  queryKey: ["github", "GetContribRepos"],
  queryFn: () => getContribRepos(),
})

export const getRepositoryWithReadmeQueryOptions = (variables: GetRepositoryWithReadmeQueryVariables) =>
  queryOptions({
  queryKey: ["github", "GetRepositoryWithReadme", variables],
  queryFn: () => getRepositoryWithReadme(variables),
})

