import type { BlogPost } from '@/types'

export const blogPosts: BlogPost[] = [
  {
    slug: 'building-terminal-website',
    title: 'Building a Terminal-Inspired Website',
    description: 'How I built this website to look and feel like Neovim in a terminal',
    date: '2024-12-08',
    tags: ['react', 'typescript', 'design', 'neovim'],
    readingTime: '5 min read',
    content: [
      '# Building a Terminal-Inspired Website',
      '',
      '## The Inspiration',
      '',
      'As a developer who spends most of their time in the terminal,',
      'I wanted my personal website to reflect that aesthetic.',
      '',
      "This site is designed to look like Ghostty running Neovim with oil.nvim.",
      "Every interaction is keyboard-driven, just like the real thing.",
      '',
      '',
      '## The Tech Stack',
      '',
      '### Frontend',
      '  - TanStack Start for full-stack React',
      '  - Tailwind CSS v4 for styling',
      '  - TypeScript for type safety',
      '',
      '### Design',
      '  - Catppuccin Mocha color scheme',
      '  - JetBrains Mono font',
      '  - Custom terminal chrome',
      '',
      '',
      '## Key Features',
      '',
      '  - oil.nvim-style navigation with j/k/Enter/-',
      '  - Vim command line with :q and :help',
      '  - Telescope-style fuzzy finder with /',
      '  - Line numbers on every page',
      '',
      '',
      '## Example Code',
      '',
      'Here is how the navigation context works:',
      '',
      '```typescript',
      'const { mode, setMode } = useNavigation()',
      '',
      'useEffect(() => {',
      '  const handleKeyDown = (e: KeyboardEvent) => {',
      '    if (mode !== "NORMAL") return',
      '    if (e.key === ":") {',
      '      setMode("COMMAND")',
      '    }',
      '  }',
      '  window.addEventListener("keydown", handleKeyDown)',
      '  return () => window.removeEventListener("keydown", handleKeyDown)',
      '}, [mode])',
      '```',
      '',
      '',
      '## What I Learned',
      '',
      'Building this site taught me a lot about:',
      '',
      '  - Managing keyboard state globally',
      '  - Creating accessible keyboard-only interfaces',
      '  - Mimicking terminal aesthetics on the web',
      '',
      '',
      '## Conclusion',
      '',
      'This was a fun project that combines my love of terminals',
      'with modern web development. Check out the source code',
      'on GitHub!',
      '',
    ],
  },
  {
    slug: 'why-i-use-neovim',
    title: 'Why I Use Neovim',
    description: 'My journey from VS Code to Neovim and why I never looked back',
    date: '2024-11-15',
    tags: ['neovim', 'productivity', 'tools'],
    readingTime: '7 min read',
    content: [
      '# Why I Use Neovim',
      '',
      '## The Beginning',
      '',
      'Like many developers, I started with VS Code.',
      "It's a great editor with excellent extensions and ease of use.",
      '',
      'But something was missing. I spent too much time reaching',
      'for the mouse, navigating menus, and clicking buttons.',
      '',
      '',
      '## The Switch',
      '',
      'I made the switch to Neovim in 2022 and never looked back.',
      '',
      'The learning curve was steep, but the payoff was worth it:',
      '',
      '  - Blazing fast startup time',
      '  - Complete keyboard control',
      '  - Infinite customization',
      '  - Runs anywhere (SSH, containers, etc.)',
      '',
      '',
      '## My Setup',
      '',
      '### Core Plugins',
      '  - lazy.nvim for plugin management',
      '  - telescope.nvim for fuzzy finding',
      '  - nvim-lspconfig for language servers',
      '  - nvim-treesitter for syntax highlighting',
      '  - oil.nvim for file navigation',
      '',
      '### Quality of Life',
      '  - which-key.nvim for keybinding hints',
      '  - gitsigns.nvim for git integration',
      '  - lualine.nvim for a pretty status line',
      '',
      '',
      '## Tips for Beginners',
      '',
      '  1. Start with a distro like LazyVim or NvChad',
      '  2. Learn the motions before customizing',
      '  3. Add plugins slowly, one at a time',
      "  4. Don't try to replicate VS Code",
      '',
      '',
      '## Conclusion',
      '',
      'Neovim has made me a more efficient developer.',
      'The initial investment pays dividends every day.',
      '',
      'Give it a try - your future self will thank you.',
      '',
    ],
  },
  {
    slug: 'my-dev-setup-2024',
    title: 'My Development Setup in 2024',
    description: 'A tour of my terminal-centric development environment',
    date: '2024-10-20',
    tags: ['setup', 'terminal', 'productivity', 'dotfiles'],
    readingTime: '6 min read',
    content: [
      '# My Development Setup in 2024',
      '',
      '## Overview',
      '',
      "Here's a tour of my current development setup.",
      "It's heavily terminal-focused and optimized for speed.",
      '',
      '',
      '## Hardware',
      '',
      '  - MacBook Pro M3 Max',
      '  - 32GB RAM',
      '  - 1TB SSD',
      '  - Studio Display',
      '',
      '',
      '## Terminal',
      '',
      '### Ghostty',
      '',
      'Ghostty is my terminal of choice. It offers:',
      '',
      '  - GPU-accelerated rendering',
      '  - Native macOS integration',
      '  - Excellent font rendering',
      '  - Low latency input',
      '',
      '',
      '## Shell',
      '',
      '### Zsh + Starship',
      '',
      'I use Zsh with the Starship prompt for:',
      '',
      '  - Fast, minimal prompt',
      '  - Git status at a glance',
      '  - Language version display',
      '',
      '',
      '## Editor',
      '',
      'Neovim, of course! See my other post for details.',
      '',
      '',
      '## Other Tools',
      '',
      '  - tmux for session management',
      '  - lazygit for git operations',
      '  - ripgrep for fast searching',
      '  - fzf for fuzzy finding',
      '  - zoxide for smart cd',
      '',
      '',
      '## Dotfiles',
      '',
      'All my configuration is managed with:',
      '',
      '  - chezmoi for dotfile management',
      '  - GitHub for version control',
      '  - Automated setup scripts',
      '',
      '',
      '## Conclusion',
      '',
      'A well-tuned development environment is a joy to use.',
      'Invest time in your tools - they pay dividends.',
      '',
    ],
  },
]

/**
 * Get a blog post by slug
 */
export function getBlogPost(slug: string): BlogPost | undefined {
  return blogPosts.find((post) => post.slug === slug)
}

/**
 * Get all blog posts sorted by date (newest first)
 */
export function getAllBlogPosts(): BlogPost[] {
  return [...blogPosts].sort(
    (a, b) => new Date(b.date).getTime() - new Date(a.date).getTime()
  )
}
