import type { BlogPost } from '@/types'

export const blogPosts: BlogPost[] = [
  {
    slug: 'building-terminal-website',
    title: 'Building a Terminal-Inspired Website',
    description: 'How I built this website to look and feel like Neovim in a terminal',
    date: '2024-12-08',
    tags: ['react', 'typescript', 'design', 'neovim'],
    readingTime: '5 min read',
    content: [
      '# Building a Terminal-Inspired Website',
      '',
      '## The Inspiration',
      '',
      'As a developer who spends most of their time in the terminal,',
      'I wanted my personal website to reflect that aesthetic.',
      '',
      "This site is designed to look like Ghostty running Neovim with oil.nvim.",
      "Every interaction is keyboard-driven, just like the real thing.",
      '',
      '',
      '## The Tech Stack',
      '',
      '### Frontend',
      '  - TanStack Start for full-stack React',
      '  - Tailwind CSS v4 for styling',
      '  - TypeScript for type safety',
      '',
      '### Design',
      '  - Catppuccin Mocha color scheme',
      '  - JetBrains Mono font',
      '  - Custom terminal chrome',
      '',
      '',
      '## Key Features',
      '',
      '  - oil.nvim-style navigation with j/k/Enter/-',
      '  - Vim command line with :q and :help',
      '  - Telescope-style fuzzy finder with /',
      '  - Line numbers on every page',
      '',
      '',
      '## Example Code',
      '',
      'Here is how the navigation context works:',
      '',
      '```typescript',
      'const { mode, setMode } = useNavigation()',
      '',
      'useEffect(() => {',
      '  const handleKeyDown = (e: KeyboardEvent) => {',
      '    if (mode !== "NORMAL") return',
      '    if (e.key === ":") {',
      '      setMode("COMMAND")',
      '    }',
      '  }',
      '  window.addEventListener("keydown", handleKeyDown)',
      '  return () => window.removeEventListener("keydown", handleKeyDown)',
      '}, [mode])',
      '```',
      '',
      '',
      '## What I Learned',
      '',
      'Building this site taught me a lot about:',
      '',
      '  - Managing keyboard state globally',
      '  - Creating accessible keyboard-only interfaces',
      '  - Mimicking terminal aesthetics on the web',
      '',
      '',
      '## Conclusion',
      '',
      'This was a fun project that combines my love of terminals',
      'with modern web development. Check out the source code',
      'on GitHub!',
      '',
    ],
  },
  {
    slug: 'why-i-use-neovim',
    title: 'Why I Use Neovim',
    description: 'My journey from VS Code to Neovim and why I never looked back',
    date: '2024-11-15',
    tags: ['neovim', 'productivity', 'tools'],
    readingTime: '7 min read',
    content: [
      '# Why I Use Neovim',
      '',
      '## The Beginning',
      '',
      'Like many developers, I started with VS Code.',
      "It's a great editor with excellent extensions and ease of use.",
      '',
      'But something was missing. I spent too much time reaching',
      'for the mouse, navigating menus, and clicking buttons.',
      '',
      '',
      '## The Switch',
      '',
      'I made the switch to Neovim in 2022 and never looked back.',
      '',
      'The learning curve was steep, but the payoff was worth it:',
      '',
      '  - Blazing fast startup time',
      '  - Complete keyboard control',
      '  - Infinite customization',
      '  - Runs anywhere (SSH, containers, etc.)',
      '',
      '',
      '## My Setup',
      '',
      '### Core Plugins',
      '  - lazy.nvim for plugin management',
      '  - telescope.nvim for fuzzy finding',
      '  - nvim-lspconfig for language servers',
      '  - nvim-treesitter for syntax highlighting',
      '  - oil.nvim for file navigation',
      '',
      '### Quality of Life',
      '  - which-key.nvim for keybinding hints',
      '  - gitsigns.nvim for git integration',
      '  - lualine.nvim for a pretty status line',
      '',
      '',
      '## Tips for Beginners',
      '',
      '  1. Start with a distro like LazyVim or NvChad',
      '  2. Learn the motions before customizing',
      '  3. Add plugins slowly, one at a time',
      "  4. Don't try to replicate VS Code",
      '',
      '',
      '## Conclusion',
      '',
      'Neovim has made me a more efficient developer.',
      'The initial investment pays dividends every day.',
      '',
      'Give it a try - your future self will thank you.',
      '',
    ],
  },
  {
    slug: 'my-dev-setup-2024',
    title: 'My Development Setup in 2024',
    description: 'A tour of my terminal-centric development environment',
    date: '2024-10-20',
    tags: ['setup', 'terminal', 'productivity', 'dotfiles'],
    readingTime: '6 min read',
    content: [
      '# My Development Setup in 2024',
      '',
      '## Overview',
      '',
      "Here's a tour of my current development setup.",
      "It's heavily terminal-focused and optimized for speed.",
      '',
      '',
      '## Hardware',
      '',
      '  - MacBook Pro M3 Max',
      '  - 32GB RAM',
      '  - 1TB SSD',
      '  - Studio Display',
      '',
      '',
      '## Terminal',
      '',
      '### Ghostty',
      '',
      'Ghostty is my terminal of choice. It offers:',
      '',
      '  - GPU-accelerated rendering',
      '  - Native macOS integration',
      '  - Excellent font rendering',
      '  - Low latency input',
      '',
      '',
      '## Shell',
      '',
      '### Zsh + Starship',
      '',
      'I use Zsh with the Starship prompt for:',
      '',
      '  - Fast, minimal prompt',
      '  - Git status at a glance',
      '  - Language version display',
      '',
      '',
      '## Editor',
      '',
      'Neovim, of course! See my other post for details.',
      '',
      '',
      '## Other Tools',
      '',
      '  - tmux for session management',
      '  - lazygit for git operations',
      '  - ripgrep for fast searching',
      '  - fzf for fuzzy finding',
      '  - zoxide for smart cd',
      '',
      '',
      '## Dotfiles',
      '',
      'All my configuration is managed with:',
      '',
      '  - chezmoi for dotfile management',
      '  - GitHub for version control',
      '  - Automated setup scripts',
      '',
      '',
      '## Conclusion',
      '',
      'A well-tuned development environment is a joy to use.',
      'Invest time in your tools - they pay dividends.',
      '',
    ],
  },
  // Placeholder posts for testing navigation
  {
    slug: 'getting-started-with-rust',
    title: 'Getting Started with Rust',
    description: 'A beginner-friendly introduction to the Rust programming language',
    date: '2024-10-15',
    tags: ['rust', 'programming', 'tutorial'],
    readingTime: '8 min read',
    content: [
      '# Getting Started with Rust',
      '',
      'This is a placeholder post for testing navigation.',
      '',
      'Rust is a systems programming language focused on safety and performance.',
      '',
    ],
  },
  {
    slug: 'typescript-tips-and-tricks',
    title: 'TypeScript Tips and Tricks',
    description: 'Advanced TypeScript patterns for better code',
    date: '2024-10-10',
    tags: ['typescript', 'javascript', 'tips'],
    readingTime: '5 min read',
    content: [
      '# TypeScript Tips and Tricks',
      '',
      'This is a placeholder post for testing navigation.',
      '',
      'TypeScript adds static typing to JavaScript for better developer experience.',
      '',
    ],
  },
  {
    slug: 'docker-best-practices',
    title: 'Docker Best Practices',
    description: 'How to write efficient and secure Dockerfiles',
    date: '2024-10-05',
    tags: ['docker', 'devops', 'containers'],
    readingTime: '7 min read',
    content: [
      '# Docker Best Practices',
      '',
      'This is a placeholder post for testing navigation.',
      '',
      'Docker containers help ensure consistent environments across development and production.',
      '',
    ],
  },
  {
    slug: 'git-workflow-guide',
    title: 'Git Workflow Guide',
    description: 'A comprehensive guide to Git branching strategies',
    date: '2024-09-28',
    tags: ['git', 'workflow', 'collaboration'],
    readingTime: '6 min read',
    content: [
      '# Git Workflow Guide',
      '',
      'This is a placeholder post for testing navigation.',
      '',
      'A good Git workflow is essential for team collaboration.',
      '',
    ],
  },
  {
    slug: 'testing-react-components',
    title: 'Testing React Components',
    description: 'Unit and integration testing strategies for React',
    date: '2024-09-20',
    tags: ['react', 'testing', 'javascript'],
    readingTime: '9 min read',
    content: [
      '# Testing React Components',
      '',
      'This is a placeholder post for testing navigation.',
      '',
      'Testing ensures your React components work as expected.',
      '',
    ],
  },
  {
    slug: 'css-grid-deep-dive',
    title: 'CSS Grid Deep Dive',
    description: 'Mastering CSS Grid for complex layouts',
    date: '2024-09-15',
    tags: ['css', 'frontend', 'layout'],
    readingTime: '10 min read',
    content: [
      '# CSS Grid Deep Dive',
      '',
      'This is a placeholder post for testing navigation.',
      '',
      'CSS Grid is a powerful layout system for the web.',
      '',
    ],
  },
  {
    slug: 'api-design-principles',
    title: 'API Design Principles',
    description: 'Building RESTful APIs that developers love',
    date: '2024-09-10',
    tags: ['api', 'backend', 'rest'],
    readingTime: '7 min read',
    content: [
      '# API Design Principles',
      '',
      'This is a placeholder post for testing navigation.',
      '',
      'Good API design makes integration a breeze.',
      '',
    ],
  },
  {
    slug: 'vim-motions-mastery',
    title: 'Vim Motions Mastery',
    description: 'Level up your editing speed with vim motions',
    date: '2024-09-05',
    tags: ['vim', 'productivity', 'editor'],
    readingTime: '8 min read',
    content: [
      '# Vim Motions Mastery',
      '',
      'This is a placeholder post for testing navigation.',
      '',
      'Vim motions let you navigate and edit text at the speed of thought.',
      '',
    ],
  },
  {
    slug: 'database-optimization',
    title: 'Database Optimization',
    description: 'Techniques for faster database queries',
    date: '2024-08-30',
    tags: ['database', 'sql', 'performance'],
    readingTime: '6 min read',
    content: [
      '# Database Optimization',
      '',
      'This is a placeholder post for testing navigation.',
      '',
      'Optimized queries can dramatically improve application performance.',
      '',
    ],
  },
  {
    slug: 'kubernetes-fundamentals',
    title: 'Kubernetes Fundamentals',
    description: 'Container orchestration basics for developers',
    date: '2024-08-25',
    tags: ['kubernetes', 'devops', 'containers'],
    readingTime: '12 min read',
    content: [
      '# Kubernetes Fundamentals',
      '',
      'This is a placeholder post for testing navigation.',
      '',
      'Kubernetes helps manage containerized applications at scale.',
      '',
    ],
  },
  {
    slug: 'functional-programming-js',
    title: 'Functional Programming in JavaScript',
    description: 'Applying FP concepts in everyday JavaScript',
    date: '2024-08-20',
    tags: ['javascript', 'functional', 'programming'],
    readingTime: '7 min read',
    content: [
      '# Functional Programming in JavaScript',
      '',
      'This is a placeholder post for testing navigation.',
      '',
      'Functional programming promotes cleaner, more predictable code.',
      '',
    ],
  },
  {
    slug: 'web-security-basics',
    title: 'Web Security Basics',
    description: 'Protecting your web applications from common vulnerabilities',
    date: '2024-08-15',
    tags: ['security', 'web', 'backend'],
    readingTime: '8 min read',
    content: [
      '# Web Security Basics',
      '',
      'This is a placeholder post for testing navigation.',
      '',
      'Security should be a priority from day one of development.',
      '',
    ],
  },
  {
    slug: 'graphql-vs-rest',
    title: 'GraphQL vs REST',
    description: 'Comparing two popular API architectures',
    date: '2024-08-10',
    tags: ['graphql', 'rest', 'api'],
    readingTime: '6 min read',
    content: [
      '# GraphQL vs REST',
      '',
      'This is a placeholder post for testing navigation.',
      '',
      'Both GraphQL and REST have their place in modern development.',
      '',
    ],
  },
  {
    slug: 'monorepo-management',
    title: 'Monorepo Management',
    description: 'Tools and strategies for managing monorepos',
    date: '2024-08-05',
    tags: ['monorepo', 'tooling', 'architecture'],
    readingTime: '7 min read',
    content: [
      '# Monorepo Management',
      '',
      'This is a placeholder post for testing navigation.',
      '',
      'Monorepos can simplify code sharing across projects.',
      '',
    ],
  },
  {
    slug: 'state-management-patterns',
    title: 'State Management Patterns',
    description: 'Comparing different approaches to state management',
    date: '2024-07-30',
    tags: ['react', 'state', 'architecture'],
    readingTime: '9 min read',
    content: [
      '# State Management Patterns',
      '',
      'This is a placeholder post for testing navigation.',
      '',
      'Choosing the right state management approach depends on your needs.',
      '',
    ],
  },
  {
    slug: 'ci-cd-pipelines',
    title: 'CI/CD Pipelines',
    description: 'Automating your development workflow',
    date: '2024-07-25',
    tags: ['cicd', 'devops', 'automation'],
    readingTime: '8 min read',
    content: [
      '# CI/CD Pipelines',
      '',
      'This is a placeholder post for testing navigation.',
      '',
      'Continuous integration and deployment speed up development cycles.',
      '',
    ],
  },
]

/**
 * Get a blog post by slug
 */
export function getBlogPost(slug: string): BlogPost | undefined {
  return blogPosts.find((post) => post.slug === slug)
}

/**
 * Get all blog posts sorted by date (newest first)
 */
export function getAllBlogPosts(): BlogPost[] {
  return [...blogPosts].sort(
    (a, b) => new Date(b.date).getTime() - new Date(a.date).getTime()
  )
}
