/* eslint-disable */
/* This file is auto-generated by tangrams. Do not edit. */

import * as z from "zod"

// Zod Schemas
export const repositoryFieldsFragmentSchema = z.object({
  name: z.string(),
  description: z.string().nullish(),
  url: z.string(),
  stargazerCount: z.number().int(),
  forkCount: z.number().int(),
  updatedAt: z.string(),
  primaryLanguage: z.object({
  name: z.string()
}).nullish(),
  repositoryTopics: z.object({
  nodes: z.array(z.object({
  topic: z.object({
  name: z.string()
})
})).nullish()
}),
  owner: z.object({
  login: z.string()
})
})

export const getRepositoryWithReadmeQueryVariablesSchema = z.object({
  owner: z.string(),
  name: z.string()
})

export const getOwnedReposQuerySchema = z.object({
  hobbes_sh: z.object({
  ...repositoryFieldsFragmentSchema.shape
}).nullish(),
  tangrams: z.object({
  ...repositoryFieldsFragmentSchema.shape
}).nullish()
})

export const getOmnidotdevReposQuerySchema = z.object({
  rdk: z.object({
  ...repositoryFieldsFragmentSchema.shape
}).nullish(),
  backfeed_app: z.object({
  ...repositoryFieldsFragmentSchema.shape
}).nullish(),
  garden: z.object({
  ...repositoryFieldsFragmentSchema.shape
}).nullish()
})

export const getContribReposQuerySchema = z.object({
  prise: z.object({
  ...repositoryFieldsFragmentSchema.shape
}).nullish()
})

export const getRepositoryWithReadmeQuerySchema = z.object({
  repository: z.object({
  ...repositoryFieldsFragmentSchema.shape,
  object: z.object({
  text: z.string().nullish()
}).nullish()
}).nullish()
})

// TypeScript Types (inferred from Zod schemas)
export type RepositoryFieldsFragment = z.infer<typeof repositoryFieldsFragmentSchema>
export type GetRepositoryWithReadmeQueryVariables = z.infer<typeof getRepositoryWithReadmeQueryVariablesSchema>
export type GetOwnedReposQuery = z.infer<typeof getOwnedReposQuerySchema>
export type GetOmnidotdevReposQuery = z.infer<typeof getOmnidotdevReposQuerySchema>
export type GetContribReposQuery = z.infer<typeof getContribReposQuerySchema>
export type GetRepositoryWithReadmeQuery = z.infer<typeof getRepositoryWithReadmeQuerySchema>
